const express = require('express');
const router = express.Router();

const { verifyToken } = require('./endpoints/lib');
const auth = require('./endpoints/auth');
const users = require('./endpoints/users');
const dnd_data = require('./endpoints/dnd_data');

router.post('/login', auth.login);
router.post('/register', auth.register);
router.post('/logout', auth.logout);

router.get('/users', verifyToken, users.getAll);
router.get('/users/me', verifyToken, users.getMe);
router.get('/users/:id', verifyToken, users.getByID);
router.patch('/users', verifyToken, users.update);
router.patch('/users/password', verifyToken, users.updatePassword);

router.get('/dnd/ability_scores', dnd_data.getAll);
router.post('/dnd/ability_scores', dnd_data.getSpecific);
router.get('/dnd/classes', dnd_data.getAll);
router.post('/dnd/classes', dnd_data.getSpecific);
router.get('/dnd/conditions', dnd_data.getAll);
router.post('/dnd/conditions', dnd_data.getSpecific);
router.get('/dnd/damage_types', dnd_data.getAll);
router.post('/dnd/damage_types', dnd_data.getSpecific);
router.get('/dnd/equipment_categories', dnd_data.getAll);
router.post('/dnd/equipment_categories', dnd_data.getSpecific);
router.get('/dnd/equipment', dnd_data.getAll);
router.post('/dnd/equipment', dnd_data.getSpecific);
router.get('/dnd/features', dnd_data.getAll);
router.post('/dnd/features', dnd_data.getSpecific);
router.get('/dnd/languages', dnd_data.getAll);
router.post('/dnd/languages', dnd_data.getSpecific);
router.get('/dnd/levels', dnd_data.getAll);
router.post('/dnd/levels', dnd_data.getSpecific);
router.get('/dnd/magic_schools', dnd_data.getAll);
router.post('/dnd/magic_schools', dnd_data.getSpecific);
router.get('/dnd/monsters', dnd_data.getAll);
router.post('/dnd/monsters', dnd_data.getSpecific);
router.get('/dnd/proficiencies', dnd_data.getAll);
router.post('/dnd/proficiencies', dnd_data.getSpecific);
router.get('/dnd/races', dnd_data.getAll);
router.post('/dnd/races', dnd_data.getSpecific);
router.get('/dnd/skills', dnd_data.getAll);
router.post('/dnd/skills', dnd_data.getSpecific);
router.get('/dnd/spellcasting', dnd_data.getAll);
router.post('/dnd/spellcasting', dnd_data.getSpecific);
router.get('/dnd/spells', dnd_data.getAll);
router.post('/dnd/spells', dnd_data.getSpecific);
router.get('/dnd/starting_equipment', dnd_data.getAll);
router.post('/dnd/starting_equipment', dnd_data.getSpecific);
router.get('/dnd/subclasses', dnd_data.getAll);
router.post('/dnd/subclasses', dnd_data.getSpecific);
router.get('/dnd/subraces', dnd_data.getAll);
router.post('/dnd/subraces', dnd_data.getSpecific);
router.get('/dnd/traits', dnd_data.getAll);
router.post('/dnd/traits', dnd_data.getSpecific);
router.get('/dnd/trinkets', dnd_data.getAll);
router.post('/dnd/trinkets', dnd_data.getSpecific);
router.get('/dnd/weapon_properties', dnd_data.getAll);
router.post('/dnd/weapon_properties', dnd_data.getSpecific);

module.exports = router;
